### ISSUE TITLE
Error "no route and no API found with those values"

### ISSUE THREAD

**Issue by terrell** [GetSilverfin/cubscout#16]
Earlier today, HelpScout made a "transparent update" to their gateway that broke my app using this gem. This caused all of my requests to return an error of "no route and no API found with those values"

I dug around some, installed the httplog gem, and saw that the calls were being made to https://api.helpscout.net/oauth2/token instead of https://api.helpscout.net/v2/oauth2/token as directed in the documentation at https://developer.helpscout.com/mailbox-api/overview/authentication/. In other words, the /v2 part was not being included and that was generating.

I was able to get my app working again by changing a line in the oauth_client method in the config.rb to include the path of the api_prefix in the URL.

`OAuth2::Client.new(@client_id, @client_secret, site: api_prefix, token_url: '/oauth2/token')`
to
`OAuth2::Client.new(@client_id, @client_secret, site: api_prefix, token_url: "#{URI::parse(api_prefix).path}/oauth2/token")`

Here is a link to the change: https://github.com/terrell/cubscout/blob/6c63c3c08229e3427de5f9d1c0c0e9f39d3fc13c/lib/cubscout/config.rb

Hope this helps! I'm a one-man developer at my company and your gem has saved me a ton of time migrating to the new HelpScout API 2.0.

**Comment by norydev** [comment]
Hi @terrell ! 

Woaw, someone is using our gem 😍 ! Although we didn't even release it to rubygems yet 🙈
Much respect to you and thanks for your trust!

I'm looking at it and will inform you about progress.

**Comment by norydev** [comment]
Hi @terrell 

It has been fixed in #17 
I also bumped the version to v0.1.1

Thanks for pointing it out, and enjoy using the library!

**Comment by dv** [comment]
Nice speed! 👏 👏

**Comment by terrell** [comment]
Wow guys, what a quick turnaround and a much cleaner fix than my quick hack. 😃 

After you have released to Rubygems, you may want to ask HelpScout to give you all a link on their https://developer.helpscout.com/open-source/ page.

I checked out several HelpScout API 2.0 gems in Google searches and found yours to be the most complete. It's amazing how real-world use drives innovation!
